language: ruby
rvm:
- 2.3.3
deploy:
  provider: heroku
  api_key:
    secure: PYXsm8ZkIN+DnakMFSGidoBSXAHqTrWpg55dMxFfYtI9GStZzcJ4li+l1OswMiOWTXHgT46HNnAc7jIK8EtahCmRdMyyLc+4m7D4XqhwPir1tl91+8T3hw+NS8snhw/cjIYwvlvXaFydVOGtwu4MyflKPZfN7K5Ml/QMiwBd8gLdhIJccJ8qLKb+P/FC2PBezZ5K+2AhGHxd3eGugf2dtk/wUP2JybykCf3frs5IYwsOEx8mW0DS9lQ4RbS9J6ApR5krbKY3hafkkgjKsFwOMxLbgrDQnOSNgAUsGyxGxsMIprU6sClvEj+P/HE5XVlY6Q2F5txLrr1yTWGCK90NlgotwBdBfKDUJI1md/Z1P8tiBkAS98aLyM7ule1TFbNMw/uuTMa0GTbki7xErOGHbigqXNqnAAhAjoFN2VFnAXKjkt06eSx3h2kGNiS5mABEqy/pwCY7tr+J5nUoOpPi+hd77MtZ4qeMR8M6DU5OsG0A3WhIweRZZ3GHbiO4wgwNG8PWYulMY9F1vv32f/PpMZxMPQ3yI1VqKu9zU73sIGP1VxZjBchb/ZB4ZekFh+1hxYLf9KZFI94Y78NcdXDTVBo5JrtDUBz8aUuTBF01HD7NpnMKej0gN9jMA8rfJe+xOSnXXLptWzXSJCEW4IubkdjtVvXfhfGjmnzNn/jCybg=
  app: stark-atoll-89746
  on:
    repo: McKay1717/projet
  run: rake db:migrate

before_script:
  - psql -c 'create database db_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json # Format backend coverage
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json

env:
  global:
    secure: d/JIj4MhBkwPTW+JMNP6e6MAwr4q826BN9FtSC4DR2R/X8UBNsSKcEFE1AWRfS/aui17BA+9ycuFEeUBTnQWCrHYOEh2gYIkNz4SIl8Xpa1xoVqZiayzkHKbdw6l+uR38+YpcC2RyHt095W1RtSD8fE+uUjUFKAzQWGWXEuapzERRoqv5Zvhi5sOC4hqyIT/hl7r73EoQpf0V0WG3hD92dMJ9dwOu99trwz7A0NrPSf0NI+eDCGluu3oVI4XZu9t9EvJDnT5hCyOWGEpHP+6stWySkCwwmVH+mvpngv6iB2K7smqSXc8I/is29+6wZtMllsrWJADsQGKgnNNU5RqgsYxtMmHxkbgT7sgcHjqBbLEKRBWmCxvhC4PewuWOWBreEMZTYne0hKLc29L9+nrJtlVSAqYeWkOF0xO+bGgKbpHzQR8uqcXqDn6nAeJIn36RVT1b1kmzHS9LO4+D6UKAkd3pbQJWXqk69TIXQzb2j7XKvV3Npdy9cn8NNQme6kUL+5n9b6il+YIW+NUu9cplHW7DpXxLRytyY/EgD+P2FaVXsJTZtDpoS3f3gUo8/aWfHRo6OxBri4wOTiQ0X88d4NtppYurC5rEWaznR7ZUccDYFq/yISuvhtBQymQliKlpsoKudObMSgQaqGyILNHhrrVe6rOGrHswuRO+/qWOY0=
