language: ruby
rvm:
- 2.3.3
deploy:
  provider: heroku
  api_key:
    secure: PYXsm8ZkIN+DnakMFSGidoBSXAHqTrWpg55dMxFfYtI9GStZzcJ4li+l1OswMiOWTXHgT46HNnAc7jIK8EtahCmRdMyyLc+4m7D4XqhwPir1tl91+8T3hw+NS8snhw/cjIYwvlvXaFydVOGtwu4MyflKPZfN7K5Ml/QMiwBd8gLdhIJccJ8qLKb+P/FC2PBezZ5K+2AhGHxd3eGugf2dtk/wUP2JybykCf3frs5IYwsOEx8mW0DS9lQ4RbS9J6ApR5krbKY3hafkkgjKsFwOMxLbgrDQnOSNgAUsGyxGxsMIprU6sClvEj+P/HE5XVlY6Q2F5txLrr1yTWGCK90NlgotwBdBfKDUJI1md/Z1P8tiBkAS98aLyM7ule1TFbNMw/uuTMa0GTbki7xErOGHbigqXNqnAAhAjoFN2VFnAXKjkt06eSx3h2kGNiS5mABEqy/pwCY7tr+J5nUoOpPi+hd77MtZ4qeMR8M6DU5OsG0A3WhIweRZZ3GHbiO4wgwNG8PWYulMY9F1vv32f/PpMZxMPQ3yI1VqKu9zU73sIGP1VxZjBchb/ZB4ZekFh+1hxYLf9KZFI94Y78NcdXDTVBo5JrtDUBz8aUuTBF01HD7NpnMKej0gN9jMA8rfJe+xOSnXXLptWzXSJCEW4IubkdjtVvXfhfGjmnzNn/jCybg=
  app: stark-atoll-89746
  on:
    repo: McKay1717/projet
  run: rake db:migrate
before_script:
- psql -c 'create database db_test;' -U postgres
addons:
  code_climate:
    repo_token:
	secure: GbbowtJRJFyhJihFY/K4n83gBlTvdySpHCwLi0tQ+Pup6/fMCo0mUzIRJa6DsCDPtZm1Pvh8mNrFqmGqK0462OAc9dIl5zvjnSs/QUO3uxO2jxzI/0BO8Q9vGqqcRoITdTuX4FNWTyl0sriQeJjvUnvC7egxv7S9P1aDtGjjiSWABZI+DkzZM9G0QwR75jbKSCQV5KpIVJMKLG8cs+UW4EjPxeJLrUS94uhXjiNbuYRkIj+O8sfZmK0tpCt9Zkvyo+p9KnMFsDQ133w5mZepGHWVoaoOe54saitGbpDlRav42qOCmJKg2WQ/mjpY8qoE8pKiVYz5t6kng3bJy4KpsDK6Sux90tkCWsqFbPVn2bi2B10WIBC/d+kjWYdA1sFHbz7DrXXLaYsAOmQms1hg8Cz/E1mG1W5yxqOufjWrOpPUwVuJ1CYCyGbhSBZ9MrpcPxoanOH6bl2Kn4P3KLLk2MIsImtYWkpRlJk6d/0Kb1oYYCmiLa3KtfnGJUjmWJuzzHMEtXa5CIftoDYFgTUqtmIZMyj/sda9bHQoCRmiJAB3UxJxJH2mu37V191FjTYLhIRchsSRxKHVijtYUXgTkDYNEtdnG471obruEmWX7mXMST8K22JQ5l0Q4dXDJwiiQHpEgpY+Et4NSahaZ7SeDpl2X8M3CMiFEBJ5sjz2Xw0=
